// frontend/src/components/Info.vue
<template>
  <section>
    <h1>About</h1>
    <p>
      Nebula Silva is a black metal band from Switzerland, formed in 2015 and composed of 2 members.<br />
      Bass and vocals are performed by Mick.
      Guitar and drums by Slordef.
    </p>
    <p>
      The band talks about the disasters of the world, the human condition and the universe.
    </p>
    <p>
      More to come...
    </p>
  </section>
</template>
<script setup lang="ts">
</script>

// frontend/src/Info.svelte
<section>
    <h1>About</h1>
    <p>
        Nebula Silva is a black metal band from Switzerland, formed in 2015 and composed of 2 members.<br />
        Bass and vocals are performed by Mick.
        Guitar and drums by Slordef.
    </p>
    <p>
        The band talks about the disasters of the world, the human condition and the universe.
    </p>
    <p>
        More to come...
    </p>
</section>
